import React, { useState, useEffect } from 'react';
import Snowfall from './components/Snowfall';
import DayDoor from './components/DayDoor';
import ContentModal from './components/ContentModal';
import { isFutureDay } from './utils/time';
import { DayContent } from './types';

// Total days in Advent Calendar
const TOTAL_DAYS = 25;

const App: React.FC = () => {
  const [openedDays, setOpenedDays] = useState<number[]>([]);
  const [contentCache, setContentCache] = useState<Record<number, DayContent>>({});
  const [selectedDay, setSelectedDay] = useState<number | null>(null);

  // Load state from local storage on mount
  useEffect(() => {
    const savedOpened = localStorage.getItem('openedDays');
    const savedCache = localStorage.getItem('contentCache');
    
    if (savedOpened) {
      setOpenedDays(JSON.parse(savedOpened));
    }
    if (savedCache) {
      setContentCache(JSON.parse(savedCache));
    }
  }, []);

  // Save state to local storage whenever it changes
  useEffect(() => {
    localStorage.setItem('openedDays', JSON.stringify(openedDays));
  }, [openedDays]);

  useEffect(() => {
    localStorage.setItem('contentCache', JSON.stringify(contentCache));
  }, [contentCache]);

  const handleOpenDoor = (day: number) => {
    if (!openedDays.includes(day)) {
      setOpenedDays(prev => [...prev, day]);
    }
    setSelectedDay(day);
  };

  const handleContentGenerated = (day: number, content: DayContent) => {
    setContentCache(prev => ({ ...prev, [day]: content }));
  };

  const handleCloseModal = () => {
    setSelectedDay(null);
  };

  // Generate numbers 1 to 25
  const days = Array.from({ length: TOTAL_DAYS }, (_, i) => i + 1);

  return (
    <div className="min-h-screen relative font-sans text-white">
      {/* Background Visuals */}
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-900 via-[#0B1026] to-[#050814] -z-10" />
      <Snowfall />

      {/* Main Container */}
      <div className="relative z-10 container mx-auto px-4 py-8 md:py-12 max-w-6xl">
        
        {/* Header */}
        <header className="text-center mb-12 space-y-4">
          <div className="inline-block relative">
            <h1 className="text-4xl md:text-6xl font-serif font-bold text-transparent bg-clip-text bg-gradient-to-r from-xmas-gold via-yellow-200 to-xmas-gold drop-shadow-[0_2px_2px_rgba(0,0,0,0.8)] animate-shimmer bg-[length:200%_auto]">
              聖誕倒數日曆
            </h1>
            <div className="absolute -top-6 -right-8 text-4xl animate-bounce-slow">🎅</div>
          </div>
          <p className="text-slate-300 text-lg md:text-xl font-light tracking-widest uppercase">
            Advent Calendar • Hong Kong Edition
          </p>
        </header>

        {/* Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 md:gap-6">
          {days.map((day) => (
            <DayDoor
              key={day}
              day={day}
              isOpen={openedDays.includes(day)}
              isLocked={isFutureDay(day)}
              onOpen={handleOpenDoor}
            />
          ))}
        </div>

        {/* Footer */}
        <footer className="mt-16 text-center text-slate-500 text-sm">
          <p>Made with 🎄 & React Gemini AI</p>
          <p className="mt-2 text-xs opacity-50">Content generated by AI. Timezone: Asia/Hong_Kong</p>
        </footer>
      </div>

      {/* Modal */}
      <ContentModal 
        day={selectedDay} 
        onClose={handleCloseModal}
        cachedContent={selectedDay ? contentCache[selectedDay] : undefined}
        onContentGenerated={handleContentGenerated}
      />
    </div>
  );
};

export default App;
